### ISSUE TITLE
Input Files for the ITOP dataset

### ISSUE THREAD

**Issue by Shreyas-NR** [zhangboshen/A2J#56]
Hi @zhangboshen ,
I am trying to use the A2J model with the ITOP side view dataset.
Could you please help me with understanding the following doubts?
1. itop_side_mean.npy

```
>> mean = readNPY('itop_side_mean.npy')

mean =

    0.0036
   -0.0017
    0.9951
    3.4441

```
2. itop_side_std.npy
```
>> std = readNPY('itop_side_std.npy')

std =

    0.1108
    0.1426
    0.0700
    0.5404
```

What do these 4 mean and std values refer to? (**RGB+D** or **pixel values** or **image dimensions**)
How are these values calculated if I wanted to work on my own dataset?

3. itop_side_keypoints3D_test.mat 
How are the contents of this file computed? [4863x15x3] Please advise.

4. itop_side_center_test.mat
Are these the center of mass values? I went through the answers mentioned in the other issue, but I couldn't figure them out from the V2V repo. Is it calculated based on the dimensions of the **depth image dimensions in 3 coordinates** or the **RGB image dimensions in 2 coordinates**?

5. itop_side_bndbox_test.mat
Could you please direct me to the exact model Faster RCNN (ref paper / GitHub repo) used while training A2J and the test dataset evaluation?

**Comment by zhangboshen** [comment]
@Shreyas-NR 
Hi, sorry about the late response since that Ive been kind of busy recently.

1,2, Mean and std, you can refer to this problem for computing details (https://github.com/zhangboshen/A2J/issues/12);

3,  itop_side_keypoints3D_test.mat is the GT 3D keypoints in world coordinate system. this is pvrovided by the source ITOP dataset;

4, Yes, center points are the 3D center coordinate of hand, the center file we used (https://drive.google.com/drive/folders/1IkW3D8FkTLuCP8KBrpohuDQaTwAA9VpG) is actually predicted with a small network (please refer to V2V paper for more details);

5, Actually, detect bndbox of human body on ITOP is easy, you can use any mutual object detector to get the bndbox predictions. (The FRCNN repo that I used is kind of too old, implemented in matcaffe, I believe this is not a good choice for you)

**Comment by ProVival** [comment]
> @Shreyas-NR Hi, sorry about the late response since that Ive been kind of busy recently.
> 
> 1,2, Mean and std, you can refer to this problem for computing details (#12);
> 
> 3, itop_side_keypoints3D_test.mat is the GT 3D keypoints in world coordinate system. this is pvrovided by the source ITOP dataset;
> 
> 4, Yes, center points are the 3D center coordinate of hand, the center file we used (https://drive.google.com/drive/folders/1IkW3D8FkTLuCP8KBrpohuDQaTwAA9VpG) is actually predicted with a small network (please refer to V2V paper for more details);
> 
> 5, Actually, detect bndbox of human body on ITOP is easy, you can use any mature object detector to get the bndbox predictions. (The FRCNN repo that I used is kind of too old, implemented with matcaffe, I believe this is not a good choice for you)

Hi, i wanted to ask something about the given drive link for center coordinates in "ITOP front view" folder. There are lines that contains invalid invalid invalid, is it okay to just ignore them? It seems that when we ignore them it makes the center point count precisely 4863, which is the number of test images. Also while calculating mean and std, what values are you using for cropHandWidth and cropHandHeight? Thanks a lot!
